### ISSUE TITLE
Error when loading the script on clean installation

### ISSUE THREAD

**Issue by acoppes** [Cycododge/Progress-For-Trello#2]
I just installed the plugin on Chrome Version 54.0.2840.59 m and it fails.

The error exception is:

```
Uncaught ReferenceError: ModelCacheCache is not defined
    at loadData (chrome-extension://ihneehmaifakdfpbjmneobgeifcaddbd/js/bp-trello.js?v=1477007696671:350:12)
    at HTMLDivElement.continueLoad (chrome-extension://ihneehmaifakdfpbjmneobgeifcaddbd/js/bp-trello.js?v=1477007696671:287:4)
    at HTMLDivElement.opt.complete (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:7:8666)
    at fire (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:6:6726)
    at Object.add [as done] (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:6:7189)
    at Animation (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:4:26228)
    at HTMLDivElement.doAnimation (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:7:9046)
    at Function.dequeue (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:6:15561)
    at HTMLDivElement.<anonymous> (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:6:16163)
    at Function.each (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:5:1390)
    at jQuery.fn.init.each (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:4:30828)
    at jQuery.fn.init.queue (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:6:16033)
    at jQuery.fn.init.animate (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:7:9236)
    at jQuery.fn.init.jQuery.fn.(anonymous function) [as slideDown] (https://d78fikflryjgj.cloudfront.net/js/ba0ebf706626f1a9ce08ac5a3d459a25/ltp.js:7:11081)
    at injectUI (chrome-extension://ihneehmaifakdfpbjmneobgeifcaddbd/js/bp-trello.js?v=1477007696671:261:17)
    at initEvents (chrome-extension://ihneehmaifakdfpbjmneobgeifcaddbd/js/bp-trello.js?v=1477007696671:101:3)
```

**Comment by acoppes** [comment]
Tested with this fix and seems to work:

https://gist.github.com/acoppes/a16ae220fcea83d6090ca6f8ad9a1a41

**Comment by Cycododge** [comment]
Awesome thank you. I will look into applying this late next week, and getting a new version out. Thanks again.

**Comment by Cycododge** [comment]
Issue is now fixed. Update submitted to the Chrome store.
